In [247]:
import pandas as pd

In [248]:
data = pd.read_csv("train.csv")

In [249]:
data.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [226]:
data.shape

(19237, 18)

In [227]:
data.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [228]:
data["Price"].head()

0    13328
1    16621
2     8467
3     3607
4    11726
Name: Price, dtype: int64

In [229]:
data.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year',
       'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [250]:
data.rename(columns={"Fuel type": "fuel_type"}, inplace=True)

In [251]:
data

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,fuel_type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [231]:

def Price_Range(Choice):
    if Choice <300:
        return data.query('Price < 300')
    elif Choice <=300 and Choice < 600:
        return data.query('Price <=300 and Price <600')
    elif Choice >=600 and Choice < 1000:
        return data.query('Price < 1000')
    elif Choice >=1000 and Choice < 2000:
         return data.query('Price >=1000 and Price <2000')
    elif Choice >=2000 and Choice < 3000:
        return data.query('Price >=2000 and Price <3000')
    elif Choice >=3000 and Choice < 4000:
        return data.query('Price >=3000 and Price <4000')
    elif Choice >=4000 and Choice < 5000:
           return data.query('Price >=4000 and Price <5000')
    elif Choice >=5000 and Choice < 6000:
        return data.query('Price >=5000 and Price <6000')
    elif Choice >=6000 and Choice < 7000:
        return data.query('Price >=6000 and Price <7000')
    elif Choice >=7000 and Choice < 8000:
        return data.query('Price >=7000 and Price <8000')
    elif Choice >=8000 and Choice < 9000:
        return data.query('Price >=8000 and Price <9000')
    elif Choice >=9000 and Choice < 10000:
        return data.query('Price >=9000 and Price <10000')
    elif Choice >=10000 and Choice < 11000:
        return data.query('Price >=10000 and Price <11000')
    elif Choice >=11000 and Choice < 12000:
        return data.query('Price >=11000 and Price <12000')
    elif Choice >=12000 and Choice < 13000:
        return data.query('Price >=12000 and Price <13000')
    elif Choice >=13000 and Choice < 14000:
        return data.query('Price >=13000 and Price <14000')
    elif Choice >=14000 and Choice < 15000:
        return data.query('Price >=14000 and Price <15000')
    elif Choice >=15000 and Choice < 16000:
        return data.query('Price >=15000 and Price <16000')
    elif Choice >=16000 and Choice < 17000:
        return data.query('Price >=16000 and Price <17000')
    elif Choice >=18000 and Choice < 19000:
        return data.query('Price >=18000 and Price <19000')
    elif Choice >=19000 and Choice < 20000:
        return data.query('Price >=19000 and Price <20000')
    else:
        return data.query('Price >20000')

In [265]:
Value = input("Enter Price Range")
Choice = int(Value)
df_price =  Price_Range(Choice)
df_price

Enter Price Range10

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,fuel_type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
27,45804684,30,-,TOYOTA,Prius,2008,Sedan,No,Hybrid,1.5,169000 km,4.0,Automatic,Front,04-May,Left wheel,White,8
33,45770026,125,1750,TOYOTA,Highlander,2008,Sedan,Yes,Hybrid,3.3,287274 km,6.0,Automatic,4x4,04-May,Left wheel,White,12
45,45769564,220,1194,TOYOTA,Tacoma,2013,Jeep,Yes,Petrol,4,239342 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
79,45758167,220,1185,FORD,Escape,2009,Jeep,Yes,Hybrid,2.5,193614 km,4.0,Automatic,Front,04-May,Left wheel,White,0
117,45624923,94,-,HONDA,FIT,2003,Hatchback,No,Petrol,1.5,178000 km,4.0,Variator,Front,04-May,Right-hand drive,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19103,45748748,30,-,NISSAN,Tiida,2006,Hatchback,No,Petrol,1.5,0 km,4.0,Automatic,Front,04-May,Right-hand drive,Black,4
19148,45303823,30,-,HONDA,FIT,2005,Hatchback,No,Petrol,1.3,169000 km,4.0,Automatic,Front,04-May,Right-hand drive,White,4
19164,45040734,60,-,TOYOTA,Prius,2013,Sedan,No,Hybrid,1.8,150000 km,4.0,Automatic,Front,04-May,Left wheel,White,8
19218,45748699,30,-,NISSAN,Note,2006,Hatchback,No,Petrol,1.3,0 km,4.0,Automatic,Front,04-May,Right-hand drive,Green,9
19229,39977395,50,-,TOYOTA,Prius,2008,Hatchback,No,Hybrid,1.5,150000 km,4.0,Automatic,Front,04-May,Left wheel,Silver,6

In [270]:
def Fuel_Range(Fuel):
    if Fuel == "Petrol":
        return data.query('fuel_type == "Petrol"')
    elif Fuel == "Diesel":
        return data.query('fuel_type == "Diesel"')
    elif Fuel == "Hybrid":
        return data.query('fuel_type == "Hybrid"')
    elif Fuel == "CNG":
        return data.query('fuel_type == "CNG"')
    elif Fuel == "plug-in":
        return data.query('fuel_type == "plug-in"')
    elif Fuel == "PNG":
        return data.query('fuel_type == "LPG"')

data.query('fuel_type == @Fuel')

In [272]:
Fuel = "Petrol" 
df_Fuel = Fuel_Range(Fuel)
df_Fuel

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,fuel_type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118 km,4.0,Automatic,Front,04-May,Left wheel,Grey,12
9,45756839,26657,-,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,128500 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19221,45776906,15681,-,VOLKSWAGEN,Jetta,2013,Sedan,Yes,Petrol,2.5,81200 km,5.0,Manual,Front,04-May,Left wheel,Silver,12
19223,44571028,8781,-,DODGE,Caliber,2008,Hatchback,No,Petrol,2.4,0 km,4.0,Automatic,Front,04-May,Left wheel,Blue,4
19224,45768089,19130,-,KIA,Optima ex,2014,Sedan,Yes,Petrol,2.4,35800 km,4.0,Automatic,Front,04-May,Left wheel,Black,12
19226,45796788,7840,-,NISSAN,Skyline,2003,Sedan,Yes,Petrol,3,220000 km,6.0,Tiptronic,Rear,04-May,Right-hand drive,White,0
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8